### PR TITLE
upgrade to GnuCOBOL 3.2

### PR DESCRIPTION
**Pull request by axtens**
A student notified me of the fact that the documentation says `B-OR` but the current compiler doesn't take without complaint. 3.2 has been out for a while and is stable.

### CODE REVIEW

**Comment by axtens** [comment]
Looks like the tests will have to be re-examined.

**Comment by ErikSchierboom** [comment]
@axtens The expected results have changed a bit with this change. The easiest way to remedy this is to:

1. Run `./bin/run-tests-in-docker.sh`
2. Run `find tests -name results.json -execdir cp results.json expected_results.json \;`
3. Inspect the git diff to see if the changes make sense
4. If they do, update the PR

**Comment by axtens** [comment]
Thank you!

**Comment by axtens** [comment]
@ErikSchierboom PR updated. Ready to go.

**Review by ErikSchierboom — APPROVED** [review]
LGTM!

**Pull request merged**
